### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'types.GenericAlias'

### ISSUE THREAD

**Issue by DucNgn** [mingrammer/diagrams#1049]
I'm encountering an error while trying to follow the [quick start guide ](https://diagrams.mingrammer.com/docs/getting-started/installation)for the library. The error occurs when importing the Diagram class from the diagrams module.

Steps to Reproduce
1. Install Graphviz (already done)
2. Install diagrams using poetry: `poetry add diagrams`
3. Create a Python file with the following content:
```python
from diagrams import Cluster, Diagram
```
4. Run the python file: `poetry run python3 main.py`

```
Traceback (most recent call last):
  File "/Users/duc.nguyen/docs/main.py", line 1, in <module>
    from diagrams import Cluster, Diagram
  File "/Users/duc.nguyen/docs/.venv/lib/python3.9/site-packages/diagrams/__init__.py", line 40, in <module>
    class Diagram:
  File "/Users/duc.nguyen/docs/.venv/lib/python3.9/site-packages/diagrams/__init__.py", line 85, in Diagram
    outformat: str | list[str] = "png",
TypeError: unsupported operand type(s) for |: 'type' and 'types.GenericAlias'
```

**Comment by mingrammer** [comment]
Sorry, I fixed this issue with https://github.com/mingrammer/diagrams/pull/1052,  and will release a new fixed version.

**Comment by mingrammer** [comment]
The fixed version ([v0.24.1](https://github.com/mingrammer/diagrams/releases/tag/v0.24.1)) is now released.

**Comment by HenryBao91** [comment]
> The fixed version ([v0.24.1](https://github.com/mingrammer/diagrams/releases/tag/v0.24.1)) is now released.

I installed this version, but here is a problem:
```
 henry@master  python -c "from diagrams import Diagram"                                        
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/henry/src/miniconda3/lib/python3.8/site-packages/diagrams/__init__.py", line 40, in <module>
    class Diagram:
  File "/Users/henry/src/miniconda3/lib/python3.8/site-packages/diagrams/__init__.py", line 85, in Diagram
    outformat: Union[str, list[str]] = "png",
TypeError: 'type' object is not subscriptable
```

**Comment by HenryBao91** [comment]
> > The fixed version ([v0.24.1](https://github.com/mingrammer/diagrams/releases/tag/v0.24.1)) is now released.
> 
> I installed this version, but here is a problem:
> 
> ```
>  henry@master  python -c "from diagrams import Diagram"                                        
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/henry/src/miniconda3/lib/python3.8/site-packages/diagrams/__init__.py", line 40, in <module>
>     class Diagram:
>   File "/Users/henry/src/miniconda3/lib/python3.8/site-packages/diagrams/__init__.py", line 85, in Diagram
>     outformat: Union[str, list[str]] = "png",
> TypeError: 'type' object is not subscriptable
> ```
<img width="898" alt="image" src="https://github.com/user-attachments/assets/8cf14614-8cc3-415c-b4ce-d82fcfa75f85" />


@mingrammer  And then, I fix it:

` vim /Users/henry/src/miniconda3/lib/python3.8/site-packages/diagrams/__init__.py`

```
class Diagram:
    # ...
    def __init__(
        self,
        name: str = "",
        filename: str = "",
        direction: str = "LR",
        curvestyle: str = "ortho",
        # outformat: Union[str, list[str]] = "png", 
        outformat: Union[str, List[str]] = "png",  #  Fix here
        autolabel: bool = False,
        show: bool = True,
        strict: bool = False,
        graph_attr: Optional[dict] = None,
        node_attr: Optional[dict] = None,
        edge_attr: Optional[dict] = None,
    ):
        ...
```

And then it run successfully.
