### ISSUE TITLE
extra attrs of Edge doesn't work

### ISSUE THREAD

**Issue by yu-iskw** [mingrammer/diagrams#113]
## Issue
I tried to pass extra edge attributes to `Edge`, but I got the error messsage. I expect we can pass any edge attributes to `**attrs` of `Edge`. 

## Code to reproduce
I put `minlen=2.0` as an extra attributes.
```test_edge_attrs.py
from diagrams import Diagram, Node, Edge

with Diagram("test Edge attrs", show=False):
  node1 = Node("node1")
  node2 = Node("node2")
  node1 - Edge(color="red", minlen=2.0) - node2
```

## Error
```
$ python test_edge_attrs.py

Traceback (most recent call last):
  File "test2.py", line 6, in <module>
    node1 - Edge(color="red", minlen=2.0) - node2
  File "/Users/yu/anaconda2/envs/python3.7/lib/python3.7/site-packages/diagrams/__init__.py", line 447, in __sub__
    return self.connect(other)
  File "/Users/yu/anaconda2/envs/python3.7/lib/python3.7/site-packages/diagrams/__init__.py", line 493, in connect
    return self.node.connect(other, self)
  File "/Users/yu/anaconda2/envs/python3.7/lib/python3.7/site-packages/diagrams/__init__.py", line 385, in connect
    self._diagram.connect(self, node, edge)
  File "/Users/yu/anaconda2/envs/python3.7/lib/python3.7/site-packages/diagrams/__init__.py", line 168, in connect
    self.dot.edge(node.hashid, node2.hashid, **edge.attrs)
  File "/Users/yu/anaconda2/envs/python3.7/lib/python3.7/site-packages/graphviz/dot.py", line 146, in edge
    attr_list = self._attr_list(label, attrs, _attributes)
  File "/Users/yu/anaconda2/envs/python3.7/lib/python3.7/site-packages/graphviz/lang.py", line 126, in attr_list
    content = a_list(label, kwargs, attributes)
  File "/Users/yu/anaconda2/envs/python3.7/lib/python3.7/site-packages/graphviz/lang.py", line 100, in a_list
    for k, v in tools.mapping_items(kwargs) if v is not None]
  File "/Users/yu/anaconda2/envs/python3.7/lib/python3.7/site-packages/graphviz/lang.py", line 100, in <listcomp>
    for k, v in tools.mapping_items(kwargs) if v is not None]
  File "/Users/yu/anaconda2/envs/python3.7/lib/python3.7/site-packages/graphviz/lang.py", line 62, in quote
    if is_html_string(identifier) and not isinstance(identifier, NoHtml):
TypeError: expected string or bytes-like object
```

**Comment by yu-iskw** [comment]
Ah, I got it. We have to pass values as string like `Edge("link", minlen="2.0")`.
