### ISSUE TITLE
Control Fontsize of Node labels

### ISSUE THREAD

**Issue by farshad-hobsons** [mingrammer/diagrams#123]
I really appreciate this great project!

Is `fontsize` with `node_attr` not supported yet?

I tried testing the following 2 ways to increase the font of a node label:
### First way
```
ingress = Ingress("ingress",node_attr={"fontsize":"20"})
```
Error:
```
Traceback (most recent call last):
  File "diagram.py", line 25, in <module>
    ingress = Ingress("ingress",node_attr={"fontsize":"20"})
TypeError: __init__() got an unexpected keyword argument 'node_attr'
```
### Second way
```
ingress = Ingress("ingress",fontsize="20")
```
Error:
```
Traceback (most recent call last):
  File "diagram.py", line 25, in <module>
    ingress = Ingress("ingress",fontsize="20")
TypeError: __init__() got an unexpected keyword argument 'fontsize'
```

**Comment by mumanoha** [comment]
I think you need to use it like,

node_attr = {
    "fontsize": "8",
}
with Diagram(node_attr=node_attr)

**Comment by farshad-hobsons** [comment]
That worked. Thank you @mumanoha
