### ISSUE TITLE
I've faced bug graphviz

### ISSUE THREAD

**Issue by Fi5t** [mingrammer/diagrams#125]
Hello! When I tried to run the quick start example I got an error from graphviz.
```python
from diagrams import Diagram
from diagrams.aws.compute import EC2
from diagrams.aws.database import RDS
from diagrams.aws.network import ELB

with Diagram("Web Service", show=False):
    ELB("lb") >> EC2("web") >> RDS("userdb")
```

```
2020-05-07 08:08:05.031 dot[13140:400048] +[__NSCFConstantString length]: unrecognized selector sent to class 0x7fff8e4b84e0
2020-05-07 08:08:05.032 dot[13140:400048] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[__NSCFConstantString length]: unrecognized selector sent to class 0x7fff8e4b84e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff368b9d07 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6f4445bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff36938be7 __CFExceptionProem + 0
	3   CoreFoundation                      0x00007fff3681e57b ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff3681df58 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x00007fff367d1778 CFStringCompareWithOptionsAndLocale + 72
	6   ImageIO                             0x00007fff396f9bfe _ZN17IIO_ReaderHandler15readerForUTTypeEPK10__CFString + 50
	7   ImageIO                             0x00007fff396f9a21 _ZN14IIOImageSource14extractOptionsEP13IIODictionary + 155
	8   ImageIO                             0x00007fff39727211 CGImageSourceCreateWithDataProvider + 213
	9   libgvplugin_quartz.6.dylib          0x000000010c90ac5c quartz_loadimage_quartz + 224
	10  libgvc.6.dylib                      0x000000010c86a9bd gvloadimage + 269
	11  libgvc.6.dylib                      0x000000010c869a21 gvrender_usershape + 956
	12  libgvc.6.dylib                      0x000000010c8976ba poly_gencode + 2168
	13  libgvc.6.dylib                      0x000000010c8a3b41 emit_node + 1025
	14  libgvc.6.dylib                      0x000000010c8a28d0 emit_graph + 5048
	15  libgvc.6.dylib                      0x000000010c8a7e4c gvRenderJobs + 4936
	16  dot                                 0x000000010c860d62 main + 697
	17  libdyld.dylib                       0x00007fff705ebcc9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Traceback (most recent call last):
  File "/tmp/mydiagrams/main.py", line 7, in <module>
    ELB("lb") >> EC2("web") >> RDS("userdb")
  File "/Users/fi5t/.local/share/virtualenvs/hld-d0YnkB8-/lib/python3.7/site-packages/diagrams/__init__.py", line 139, in __exit__
    self.render()
  File "/Users/fi5t/.local/share/virtualenvs/hld-d0YnkB8-/lib/python3.7/site-packages/diagrams/__init__.py", line 174, in render
    self.dot.render(format=self.outformat, view=self.show)
  File "/Users/fi5t/.local/share/virtualenvs/hld-d0YnkB8-/lib/python3.7/site-packages/graphviz/files.py", line 209, in render
    quiet=quiet)
  File "/Users/fi5t/.local/share/virtualenvs/hld-d0YnkB8-/lib/python3.7/site-packages/graphviz/backend.py", line 206, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/Users/fi5t/.local/share/virtualenvs/hld-d0YnkB8-/lib/python3.7/site-packages/graphviz/backend.py", line 172, in run
    output=out, stderr=err)
graphviz.backend.CalledProcessError: Command '['dot', '-Tpng', '-O', 'web_service']' died with <Signals.SIGABRT: 6>. [stderr: b"2020-05-07 08:08:05.031 dot[13140:400048] +[__NSCFConstantString length]: unrecognized selector sent to class 0x7fff8e4b84e0\n2020-05-07 08:08:05.032 dot[13140:400048] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[__NSCFConstantString length]: unrecognized selector sent to class 0x7fff8e4b84e0'\n*** First throw call stack:\n(\n\t0   CoreFoundation                      0x00007fff368b9d07 __exceptionPreprocess + 250\n\t1   libobjc.A.dylib                     0x00007fff6f4445bf objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff36938be7 __CFExceptionProem + 0\n\t3   CoreFoundation                      0x00007fff3681e57b ___forwarding___ + 1427\n\t4   CoreFoundation                      0x00007fff3681df58 _CF_forwarding_prep_0 + 120\n\t5   CoreFoundation                      0x00007fff367d1778 CFStringCompareWithOptionsAndLocale + 72\n\t6   ImageIO                             0x00007fff396f9bfe _ZN17IIO_ReaderHandler15readerForUTTypeEPK10__CFString + 50\n\t7   ImageIO                             0x00007fff396f9a21 _ZN14IIOImageSource14extractOptionsEP13IIODictionary + 155\n\t8   ImageIO                             0x00007fff39727211 CGImageSourceCreateWithDataProvider + 213\n\t9   libgvplugin_quartz.6.dylib          0x000000010c90ac5c quartz_loadimage_quartz + 224\n\t10  libgvc.6.dylib                      0x000000010c86a9bd gvloadimage + 269\n\t11  libgvc.6.dylib                      0x000000010c869a21 gvrender_usershape + 956\n\t12  libgvc.6.dylib                      0x000000010c8976ba poly_gencode + 2168\n\t13  libgvc.6.dylib                      0x000000010c8a3b41 emit_node + 1025\n\t14  libgvc.6.dylib                      0x000000010c8a28d0 emit_graph + 5048\n\t15  libgvc.6.dylib                      0x000000010c8a7e4c gvRenderJobs + 4936\n\t16  dot                                 0x000000010c860d62 main + 697\n\t17  libdyld.dylib                       0x00007fff705ebcc9 start + 1\n)\nlibc++abi.dylib: terminating with uncaught exception of type NSException\n"]
```

Do you have any ideas how to deal with it?

**Comment by mingrammer** [comment]
How did you install the graphviz?

**Comment by Fi5t** [comment]
@mingrammer `brew install graphviz`

**Comment by mingrammer** [comment]
Hm, What is your version?

**Comment by Fi5t** [comment]
graphviz: stable 2.44.0

**Comment by mingrammer** [comment]
Could you please run after this?

`brew install pango librsvg && brew reinstall graphviz`

**Comment by Fi5t** [comment]
I've checked version of my `dot` binary and found out that its version doesn't match with graphviz version. I decided to reinstall it and this solved my problem. Sorry for disturbing.

**Comment by ozlerhakan** [comment]
After checking the dot version as @Fi5t mentioned, I do the following steps to solve the problem. The dot binary now shows the correct version:

```
$ dot -V
dot - graphviz version 2.40.1 (20161225.0304)
$ brew link --overwrite graphviz
$ dot -V
dot - graphviz version 2.46.1 (20210213.1702
```
