### ISSUE TITLE
Generation script fails in case insensitive file system

### ISSUE THREAD

**Issue by avmohan** [mingrammer/diagrams#257]
Getting error:
```Traceback (most recent call last):
  File "diagram.py", line 10, in <module>
    from diagrams.oci.compute import Container
  File "/usr/local/lib/python3.8/site-packages/diagrams/oci/compute.py", line 77, in <module>
    VirtualMachine = Vm
NameError: name 'Vm' is not defined```

/usr/local/lib/python3.8/site-packages/diagrams/oci/compute.py contains below:
```
 71 class VM(_Compute):
 72     _icon = "vm.png"
 73
 74
 75 # Aliases
 76
 77 VirtualMachine = Vm
```
Note the case difference VM vs Vm in classname and the alias assignment

**Comment by mingrammer** [comment]
Sorry for it! I fixed a alias key for OCI. Thank you for reporting it!

**Comment by mingrammer** [comment]
Sorry about it! I fixed an alias key for OCI. Thank you for reporting it!
