### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by resparis** [mingrammer/diagrams#366]
HI, Iam having the following error with one of the examples

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\graphviz\backend.py", line 159, in run
    proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
  File "C:\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/rober/Documents/python/diagram.py", line 7, in <module>
    ELB("lb") >> EC2("web") >> RDS("userdb")
  File "C:\Python38\lib\site-packages\diagrams\__init__.py", line 147, in __exit__
    self.render()
  File "C:\Python38\lib\site-packages\diagrams\__init__.py", line 189, in render
    self.dot.render(format=self.outformat, view=self.show, quiet=True)
  File "C:\Python38\lib\site-packages\graphviz\files.py", line 207, in render
    rendered = backend.render(self._engine, format, filepath,
  File "C:\Python38\lib\site-packages\graphviz\backend.py", line 206, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "C:\Python38\lib\site-packages\graphviz\backend.py", line 162, in run
    raise ExecutableNotFound(cmd)
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpng', '-O', 'web_service'], make sure the Graphviz executables are on your systems' PATH

**Comment by addict3d** [comment]
> graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpng', '-O', 'web_service'], make sure the Graphviz executables are on your systems' PATH

Hello. This error means you are missing the `dot` executable in that environment.

The `dot` program is provided by [Graphviz](https://graphviz.org/). Please install that and retry the example.

**Comment by AIGeneratedUsername** [comment]
@addict3d thank you, that worked. 

But it is weird that a README does not have such information and people must search for a solution.
