### ISSUE TITLE
Can't execute Example diagram

### ISSUE THREAD

**Issue by augurer** [mingrammer/diagrams#403]
I spun up a new Windows Server 2019 Virtual Machine in Microsoft Azure, installed Visual Studio Code, Cmder, Chocolatey, Python 3.9, GraphViz, and Diagrams as described in this project's documentation. When I attempt to execute the Quick Start sample, I get this output:

> C:\Source\diagrams
> λ python diagram.py
> Traceback (most recent call last):
>   File "C:\Source\diagrams\diagram.py", line 8, in <module>
>     ELB("lb") >> EC2("web") >> RDS("userdb")
>   File "C:\Python39\lib\site-packages\diagrams\__init__.py", line 149, in __exit__
>     self.render()
>   File "C:\Python39\lib\site-packages\diagrams\__init__.py", line 191, in render
>     self.dot.render(format=self.outformat, view=self.show, quiet=True)
>   File "C:\Python39\lib\site-packages\graphviz\files.py", line 207, in render
>     rendered = backend.render(self._engine, format, filepath,
>   File "C:\Python39\lib\site-packages\graphviz\backend.py", line 206, in render
>     run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
>   File "C:\Python39\lib\site-packages\graphviz\backend.py", line 171, in run
>     raise CalledProcessError(proc.returncode, cmd,
> graphviz.backend.CalledProcessError: Command '['dot', '-Tpng', '-O', 'web_service']' returned non-zero exit status 1. [stderr: b'Format: "png" not recognized. Use one of:\r\n']

What am I doing wrong?

**Comment by dmcken** [comment]
The windows version of graphviz seems to require some configuration of the plugins.

If you execute just dot in a command prompt you will likely get the following error:

```
There is no layout engine support for "dot"
Perhaps "dot -c" needs to be run (with installer's privileges) to register the plugins?
```

Open an command prompt with admin privileges and execute "dot -c" and you should be good to go.
