### ISSUE TITLE
Cannot add more than one element with diagrams.k8s.compute.Job

### ISSUE THREAD

**Issue by brianbruggeman** [mingrammer/diagrams#540]
Simple example:

```
from diagrams import Cluster, Diagram
from diagrams.k8s.compute import Job


with Diagram("Job Test"):
    with Cluster("Jobs"):
        ingestion = Job("Ingest Job")
        egestion = Job("Egest Job")
        
```

Failure:

```
Traceback (most recent call last):
  File "guides/architecture.py", line 34, in <module>
    build_diagram(output_path=args.output_path)
  File "guides/architecture.py", line 25, in build_diagram
    egestion = Job("Egest Job")
  File "<redacted-venv-path>/lib/python3.8/site-packages/diagrams/__init__.py", line 149, in __exit__
    self.render()
  File "<redacted-venv-path>/lib/python3.8/site-packages/diagrams/__init__.py", line 191, in render
    self.dot.render(format=self.outformat, view=self.show, quiet=True)
  File "<redacted-venv-path>/lib/python3.8/site-packages/graphviz/files.py", line 243, in render
    rendered = backend.render(self._engine, format, filepath,
  File "<redacted-venv-path>/lib/python3.8/site-packages/graphviz/backend.py", line 223, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "<redacted-venv-path>/lib/python3.8/site-packages/graphviz/backend.py", line 183, in run
    raise CalledProcessError(proc.returncode, cmd,
graphviz.backend.CalledProcessError: Command '['dot', '-Kdot', '-Tpng', '-O', 'architecture']' died with <Signals.SIGABRT: 6>. [stderr: b'']
make: *** [guide-build] Error 1
```

**Comment by clayms** [comment]
@brianbruggeman  your code works for me.  

What versions of everything are you using?

```bash
$ dot -V
dot - graphviz version 2.30.1 (20180828.1746)
```

```bash
$ pip list

Package                       Version            
----------------------------- -------------------
...
diagrams                      0.19.1             
...        
graphviz                      0.16  
...
```

```bash
$ cat /etc/*-release

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)
```

**Comment by brianbruggeman** [comment]
I'm going to close this, because I'm no longer invested in the outcome.

My work-around was to use Docker.
