### ISSUE TITLE
Windows "out of memory"

### ISSUE THREAD

**Issue by chlsmith** [mingrammer/diagrams#546]
using the following code:

`from diagrams import Diagram
from diagrams.aws.compute import EC2
from diagrams.aws.database import RDS
from diagrams.aws.network import ELB

with Diagram("WebService", show=True):
    ELB("lb") >> EC2("web") >> RDS("userdb")`

I'm getting the following error .  This is running on Windows, tried using both the Chocolatey installation of Graphviz and the executable downloaded installation.
  
'Traceback (most recent call last):
  File ".\diagram.py", line 7, in <module>
    ELB("lb") >> EC2("web") >> RDS("userdb")
  File "C:\Python368\lib\site-packages\diagrams\__init__.py", line 149, in __exit__
    self.render()
  File "C:\Python368\lib\site-packages\diagrams\__init__.py", line 191, in render
    self.dot.render(format=self.outformat, view=self.show, quiet=True)
  File "C:\Python368\lib\site-packages\graphviz\files.py", line 245, in render
    quiet=quiet)
  File "C:\Python368\lib\site-packages\graphviz\backend.py", line 223, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "C:\Python368\lib\site-packages\graphviz\backend.py", line 184, in run
    output=out, stderr=err)
graphviz.backend.CalledProcessError: Command '['dot', '-Kdot', '-Tpng', '-O', 'web_service']' returned non-zero exit status 1. [stderr: b'out of memory\r\n']'

**Comment by chlsmith** [comment]
Standard laptop setup .  Windows 10, 16 GB Ram, etc.

**Comment by cdemi** [comment]
I also have this issue but it looks like it's coming from graphviz and not diagrams

```
Traceback (most recent call last):
  File "diagram.py", line 7, in <module>
    ELB("lb") >> EC2("web") >> RDS("userdb")
  File "C:\Users\chris\AppData\Roaming\Python\Python38\site-packages\diagrams\__init__.py", line 149, in __exit__
    self.render()
  File "C:\Users\chris\AppData\Roaming\Python\Python38\site-packages\diagrams\__init__.py", line 191, in render
    self.dot.render(format=self.outformat, view=self.show, quiet=True)
  File "C:\Users\chris\AppData\Roaming\Python\Python38\site-packages\graphviz\files.py", line 243, in render
    rendered = backend.render(self._engine, format, filepath,
  File "C:\Users\chris\AppData\Roaming\Python\Python38\site-packages\graphviz\backend.py", line 223, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "C:\Users\chris\AppData\Roaming\Python\Python38\site-packages\graphviz\backend.py", line 183, in run
    raise CalledProcessError(proc.returncode, cmd,
graphviz.backend.CalledProcessError: Command '['dot', '-Kdot', '-Tpng', '-O', 'web_service']' returned non-zero exit status 1. [stderr: b'out of memory\r\n']
```

**Comment by DenisVasiliev** [comment]
I had same problem. Update to graphviz 2.47.3 fixed it for me.
