### ISSUE TITLE
poetry install failed

### ISSUE THREAD

**Issue by chenlujjj** [mingrammer/diagrams#672]
Package operations: 23 installs, 0 updates, 0 removals

  • Installing lazy-object-proxy (1.4.3): Failed

  EnvCommandError

  Command ['/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/bin/pip', 'install', '--no-deps', 'file:///Users/chenluxin/Library/Caches/pypoetry/artifacts/7b/47/b3/1ffa7ffb9569bd18b424750eac29f7dc67940ec405dc986a6caddbf890/lazy-object-proxy-1.4.3.tar.gz'] errored with the following return code 2, and output:
  Looking in indexes: http://pypi.douban.com/simple, https://pypi.tuna.tsinghua.edu.cn/simple
  Processing /Users/chenluxin/Library/Caches/pypoetry/artifacts/7b/47/b3/1ffa7ffb9569bd18b424750eac29f7dc67940ec405dc986a6caddbf890/lazy-object-proxy-1.4.3.tar.gz
    Installing build dependencies: started
    ERROR: Error expected str, bytes or os.PathLike object, not NoneType while executing command /Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/bin/python /Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/6f/cgm11n_n6r1_960qs_vks9840000gn/T/pip-build-env-wka07pey/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i http://pypi.douban.com/simple --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.douban.com --trusted-host '' --trusted-host pypi.tuna.tsinghua -- 'setuptools>=30.3.0' wheel 'setuptools_scm>=3.3.1'
    Installing build dependencies: finished with status 'error'
  ERROR: Exception:
  Traceback (most recent call last):
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
      status = run_func(*args)
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
      return func(self, options, args)
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 339, in run
      reqs, check_supported_wheels=not options.target_dir
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
      collected = self.factory.collect_root_requirements(root_reqs)
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 470, in collect_root_requirements
      requested_extras=(),
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 435, in _make_requirement_from_install_req
      version=None,
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
      version=version,
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 287, in __init__
      version=version,
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
      self.dist = self._prepare()
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
      dist = self._prepare_distribution()
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 292, in _prepare_distribution
      return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
      return self._prepare_linked_requirement(req, parallel_builds)
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 550, in _prepare_linked_requirement
      self.build_isolation,
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
      abstract_dist.prepare_distribution_metadata(finder, build_isolation)
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/distributions/sdist.py", line 37, in prepare_distribution_metadata
      self._prepare_build_backend(finder)
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/distributions/sdist.py", line 59, in _prepare_build_backend
      finder, pyproject_requires, "overlay", "Installing build dependencies"
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/build_env.py", line 211, in install_requirements
      message,
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/build_env.py", line 263, in _install_requirements
      call_subprocess(args, spinner=spinner, extra_environ=extra_environ)
    File "/Users/chenluxin/Library/Caches/pypoetry/virtualenvs/diagrams-zi7GzVs5-py3.6/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 187, in call_subprocess
      errors="backslashreplace",
    File "/Users/chenluxin/.pyenv/versions/3.6.15/lib/python3.6/subprocess.py", line 729, in __init__
      restore_signals, start_new_session)
    File "/Users/chenluxin/.pyenv/versions/3.6.15/lib/python3.6/subprocess.py", line 1295, in _execute_child
      restore_signals, start_new_session, preexec_fn)
  TypeError: expected str, bytes or os.PathLike object, not NoneType

  at /usr/local/lib/python3.9/site-packages/poetry/utils/env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│
      1197│         return decode(output)
      1198│
      1199│     def execute(self, bin, *args, **kwargs):

**Comment by chenlujjj** [comment]
Seems like something wrong with lazy-object-proxy-1.4.3 lib
