### ISSUE TITLE
ModuleNotFoundError: No module named 'diagrams'

### ISSUE THREAD

**Issue by eliassal** [mingrammer/diagrams#886]
Hi, I have installed diagrams on a windows 10 with python 3.8.3 went succesfully. Whereever I run the diagram.py I get the following errors
In powershell
`python C:\Projects\Python\Diagram\diagram.py`
i get
![image](https://user-images.githubusercontent.com/8447864/234081747-dbb91880-8c6b-4213-b315-371e6d4a81ef.png)

Inside  IDLE

Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    from diagrams import Diagram
ImportError: No module named diagrams

inside visual studio code

![image](https://user-images.githubusercontent.com/8447864/234082153-36579b6e-6921-41b5-ac1a-0acbac629c73.png)

**Comment by eliassal** [comment]
I even tried on a ubuntu box, again install was succerssfull

```
:~$ pip install diagrams
Defaulting to user installation because normal site-packages is not writeable
Collecting diagrams
  Downloading diagrams-0.23.3-py3-none-any.whl (24.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.4/24.4 MB 7.3 MB/s eta 0:00:00
Requirement already satisfied: jinja2<4.0,>=2.10 in /usr/lib/python3/dist-packages (from diagrams) (3.0.3)
Collecting typed-ast<2.0.0,>=1.5.4
  Downloading typed_ast-1.5.4-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (877 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 877.7/877.7 KB 4.1 MB/s eta 0:00:00
Collecting graphviz<0.21.0,>=0.13.2
  Downloading graphviz-0.20.1-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.0/47.0 KB 493.9 kB/s eta 0:00:00
Installing collected packages: typed-ast, graphviz, diagrams
Successfully installed diagrams-0.23.3 graphviz-0.20.1 typed-ast-1.5.4
```

when I run 
`python3 diagram.py`

I get same errors

```
:~$ python3 diagram.py
Traceback (most recent call last):
  File "/home/salam/.local/lib/python3.10/site-packages/graphviz/backend/execute.py", line 81, in run_check
    proc = subprocess.run(cmd, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('dot')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/salam/diagram.py", line 7, in <module>
    with Diagram("Web Service", show=False):
  File "/home/salam/.local/lib/python3.10/site-packages/diagrams/__init__.py", line 158, in __exit__
    self.render()
  File "/home/salam/.local/lib/python3.10/site-packages/diagrams/__init__.py", line 192, in render
    self.dot.render(format=self.outformat, view=self.show, quiet=True)
  File "/home/salam/.local/lib/python3.10/site-packages/graphviz/_tools.py", line 171, in wrapper
    return func(*args, **kwargs)
  File "/home/salam/.local/lib/python3.10/site-packages/graphviz/rendering.py", line 122, in render
    rendered = self._render(*args, **kwargs)
  File "/home/salam/.local/lib/python3.10/site-packages/graphviz/_tools.py", line 171, in wrapper
    return func(*args, **kwargs)
  File "/home/salam/.local/lib/python3.10/site-packages/graphviz/backend/rendering.py", line 324, in render
    execute.run_check(cmd,
  File "/home/salam/.local/lib/python3.10/site-packages/graphviz/backend/execute.py", line 84, in run_check
    raise ExecutableNotFound(cmd) from e
graphviz.backend.execute.ExecutableNotFound: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH
```

**Comment by DisSupEng** [comment]
Did you install graphviz before running `pip install diagrams`? On Ubuntu you can install it using `sudo apt install graphviz`.

Installation instructions for graphviz: https://graphviz.gitlab.io/download/

**Comment by eliassal** [comment]
Thanks, no, as I am new to python and all stuff around it, I just followed your instructions. I did setup graphviz after your response and it works like a charm now. I think it6 would be great if you indicate this somewhere as a prerequisite to new comers and especially who does not know very well python and its issues like me :-)
So many thanks again for this useful tool. Also if you allow me, your examples are only around AWS, is there examples for Azure?

**Comment by DisSupEng** [comment]
Not a problem. I'm not the owner of the repository just someone who uses it like yourself. 

I don't see any specific examples for Azure but some examples can be found here: https://diagrams.mingrammer.com/docs/getting-started/examples

Hopefully you can find a similar one and adapt it to Azure.

**Comment by DisSupEng** [comment]
@mingrammer I think this can be closed. The issue appears to be resolved.

Kind Regards
