### ISSUE TITLE
Diagrams code issue possibly due to python 3.11.x

### ISSUE THREAD

**Issue by jahway603** [mingrammer/diagrams#921]
I went to update my network diagram I'd written a while ago (which had been working perfectly fine), but it's now giving me a new error message and I believe it may be an issue with python 3.11.x

I'm now running the following version of Python:
```
$ python --version
Python 3.11.3
```

This is the error I'm receiving:
```
$ python my-diagram.py 
Traceback (most recent call last):
  File "/<OMIT PATH>/python/my-diagram.py", line 3, in <module>
    from diagrams import Cluster, Diagram, Edge
ImportError: cannot import name 'Cluster' from 'diagrams' (unknown location)
```

I also received a similar error `ImportError: cannot import name 'Diagram' from 'diagrams' (unknown location)` when attempting to run the example quick start in the documentation here
https://diagrams.mingrammer.com/docs/getting-started/installation#quick-start

**Comment by bfrevel** [comment]
I can confirm the issue

```
(.venv) ➜  diagrams git:(main) ✗ python -V
Python 3.11.5
(.venv) ➜  diagrams git:(main) ✗ pip install diagrams
Requirement already satisfied: diagrams in ./.venv/lib/python3.11/site-packages (0.23.3)
Requirement already satisfied: graphviz<0.21.0,>=0.13.2 in ./.venv/lib/python3.11/site-packages (from diagrams) (0.20.1)
Requirement already satisfied: jinja2<4.0,>=2.10 in ./.venv/lib/python3.11/site-packages (from diagrams) (3.1.2)
Requirement already satisfied: typed-ast<2.0.0,>=1.5.4 in ./.venv/lib/python3.11/site-packages (from diagrams) (1.5.5)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.11/site-packages (from jinja2<4.0,>=2.10->diagrams) (2.1.3)
(.venv) ➜  diagrams git:(main) ✗ python diagrams.py
Traceback (most recent call last):
  File "./diagrams.py", line 1, in <module>
    from diagrams import Diagram
  File "./diagrams.py", line 1, in <module>
    from diagrams import Diagram
ImportError: cannot import name 'Diagram' from partially initialized module 'diagrams' (most likely due to a circular import) (./diagrams.py)
(.venv) ➜  diagrams git:(main) ✗ cat diagrams.py
from diagrams import Diagram
from diagrams.aws.compute import EC2
from diagrams.aws.database import RDS
from diagrams.aws.network import ELB

with Diagram("Web Service", show=False):
    ELB("lb") >> EC2("web") >> RDS("userdb")
```
