### ISSUE TITLE
TypeError: 'VPC' object does not support the context manager protocol

### ISSUE THREAD

**Issue by ruckc** [mingrammer/diagrams#946]
With this code:

```python
from diagrams import Diagram
from diagrams.aws.compute import EC2
from diagrams.aws.network import PublicSubnet, PrivateSubnet, VPC


with Diagram("diagram"):
    with VPC("vpc"):
        with PublicSubnet('1a'):
            EC2('bastion')
```

I get this error message when executing it `python test.py`

```
Traceback (most recent call last):
  File "/home/user/test.py", line 7, in <module>
    with VPC("vpc"):
TypeError: 'VPC' object does not support the context manager protocol
```

Not sure what i'm doing wrong.

I get this on Python 3.12 and 3.11.  With Python 3.10 and 3.9 I get

```
Traceback (most recent call last):
  File "/home/user/test.py", line 7, in <module>
    with VPC("vpc"):
AttributeError: __enter__
```

**Comment by Anddd7** [comment]
The Cluster and Node are different source in graphviz. So it cannot put a VPC(Node) as a Cluster. I think there are bunch of PRs making it possible (https://github.com/mingrammer/diagrams/pull/823). But the author is inactive so all those are pending ...

**Comment by Anddd7** [comment]
I create a fork to use it as a local dependency, you can check https://github.com/Anddd7/diagrams-ext/pull/1. Make a copy by your self or use my main branch.
